try :
    print("o")
    
    
except Exception as e:
    print(e)
    
    
    
    